@echo off
net user Administrator Pr@is3the$un2018
net user barf D4DnB;x#6$P{Uby
net user csandurz cYSnY94cN3p\fe\%
net user dhelmet 4sr\RNv5paCd+Ab
net user dink1 #p2C]M4?,mvCuf,v
net user dink2 t#CJ__V3?S@5Y
net user dink3 KAycSf;/8JL)qU4,
net user dink4 }!N`gv6;u\xK.PDA
net user dink5 ?u97CaK(Q+u}2zm+
net user dmatrix 6a8y?`J%8*(S;]T
net user guest w=^5T~NB?~X*_vcM
net user krbtgt Re4)~NQr5bgzLK
net user kroland Qbn;J?"CGU}L*8)n
net user lstar uwK!NG6.Gz6bC3
net user pskroob wKjF/xJt-S6^5=,
net user pvalium %j;*VJt~!3-AFrhC
net user pvespa Bdm`!L@6Jam?ba
net user yogurt (ns}+W}Q7v)BCgwb