@echo off
net user "" s3R7sIG-Tmy
net user "" 7Y?sffNS6dD
net user "" eJ'CF5x6yHg
net user "" Ij0*2eJUJkd
net user "" 4E'8YFZbsjt
net user "" t3JY2DxlsG!
net user "" 2FuHp4U!jbF
net user "" lq7$0TbdLAL
net user "" ETk6q9ivPN!
net user "" 5n'wxL7NCKx
net user "" xTwWvG8Fd5!
net user "" tIrF8Ln:l9P
net user "" $NchR8N3sNa
net user "" 5N*mmDW3Pdn
net user "" Wdre3Ds;6KC
net user "" 5tmYtHpB$9W
net user "" S1N*ihLf9jE
net user "" x5u+jAN3OAi
net user "" !wC1I3DAydx
net user "" rJBdEJ36!kp
net user "" mU3LGyd6q!T
net user "" 4Xec4lT+cHB
net user "" b7hSHYA0!qo
net user "" ZP9uDb,1Ypc
net user "" Sk5_WbY8oaV
net user "" aGC8tX6$ojF
net user "" vM0eTHBll6+
net user "" OoL6f%6fWoE
net user "" 8]rMjWtP3Sx
net user "" !sZTtl1HkW4
net user "" !OsW3Ae1sbY
net user "" T!kHGe84Cgg
net user "" -WfRWG6xn7g
net user "" i~zPE25KSds
net user "" O6luKO~sSa3
net user "" k0OMgs5!MGc
net user "" BXjdVDl4)y4
net user "" 5p9*whCLDxL
net user "" 80ZCbV,puBs
net user "" vzPMl[6f9CD
net user "" T9brZXFl!7w
net user "" 1ZB@2RyxePe
net user "" la.D6kT3JvX
net user "" 2F!cEWibK0o
net user "" yZNc3Kn3-Lt
net user "" oHPz1g6L,rG
net user "" iIJlz3lG!G6
net user "" pBVPcj\95fG
net user "" WwP7G3o?Php
net user "" K'6hSDhCzr8
pause