@echo off
net user "" sS-dd07aVKG
net user "" oH!8FKfx9qV
net user "" :2gBoULXd2e
net user "" yK4wX5OrV+k
net user "" K8x[oW2xWeO
net user "" qwa0PgT{J9D
net user "" d(sEMwYJ99k
net user "" E8hlX[5FelF
net user "" gGnv'REpA11
net user "" Wi4L$OvFc7u
net user "" dLY~evyI5V1
net user "" MSnJ9Fvh-m1
net user "" aS2Kt`6kCMf
net user "" KRLkJc6{nq9
net user "" N2qc9mz~NZR
net user "" egDm_10fFIY
net user "" m1(zgE1eKIF
net user "" UlL94otWr~K
net user "" )qtQxI23GRz
net user "" ClR-wnS27Bw
net user "" 5ACfvjj_3RH
net user "" 0rYhE%d5AiI
net user "" :tlYs9O7IIt
net user "" OwmTkW0[qJ7
net user "" 9Haoj,I9HWv
net user "" *HE3QObf1ya
net user "" CS3Rq0vcMz!
net user "" 3yszTIMQj1=
net user "" 7yBvl2JX,Gv
net user "" s{X3pcEN4eF
net user "" 8UYdZg2l$fI
net user "" Nqer`WL14Qk
net user "" 7n[4vNjACBy
net user "" s2jvSOHF,e0
net user "" nDqdc(SX03D
net user "" Px74hD'NSca
net user "" 9RqVsShGk#5
net user "" Hlb5!CVl3Yk
net user "" .V1gLPf2gdJ
net user "" gL_CgjxWI66
net user "" 8b2Mp=oqHQD
net user "" BeQ5Dm0Wwb)
net user "" AsNtpO%1Oy7
net user "" PF'Z9c3eBle
net user "" QIX0f+7zdTq
net user "" Bg70ODdq$oR
net user "" v4Z=Ln9mdEP
net user "" Rc,T6RNpmv9
net user "" ny7SK3:paSZ
net user "" dR}hOUj9c2P
pause